name: Update Representatives Data
on:
  schedule:
    - cron: '0 0 1 * *' # Runs monthly
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    
    - name: Run update script
      run: |
        pip install requests
        python update_reps.py
        
    - name: Commit changes
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        git add reps.json
        git commit -m "Update representatives data"
        git push
